CONTIKI_PROJECT = udp-client udp-server
CONTIKI=../../tools/contiki-ng

all: $(CONTIKI_PROJECT)

MODULES_REL += ../../services/ids-common
MODULES += $(CONTIKI_NG_SERVICES_DIR)/shell

include $(CONTIKI)/Makefile.include
